import { expect, test } from '@playwright/test';

test('prevented and accepted reset preserve independent names and controlled authority', async ({ page }) => {
  const errors: string[] = [];
  page.on('pageerror', error => errors.push(error.message));
  await page.goto('/iframe.html?id=migration-proofs-switch--native-reset-authority&viewMode=story');
  const form = page.getByRole('form', { name: 'Switch preferences' });
  const email = page.getByRole('switch', { name: 'Email updates', exact: true });
  const sms = page.getByRole('switch', { name: 'SMS updates', exact: true });
  const paused = page.getByRole('switch', { name: 'Paused updates', exact: true });
  const values = () => form.evaluate(element => Object.fromEntries(new FormData(element as HTMLFormElement)));
  await expect(form).toBeVisible();
  await expect(paused).toBeDisabled();
  await page.getByText('Paused updates', { exact: true }).click();
  await expect(page.getByLabel('Change requests')).toHaveText('0');
  expect(await values()).toEqual({ emailUpdates: 'email', smsUpdates: 'sms' });
  await email.focus();
  await page.keyboard.press('Space');
  await page.getByText('SMS updates', { exact: true }).click();
  await expect(page.getByLabel('Change requests')).toHaveText('1');
  await expect(sms).toBeChecked();
  await page.getByRole('button', { name: 'Reset preferences' }).click();
  await expect(email).not.toBeChecked();
  expect(await values()).toEqual({ smsUpdates: 'sms' });
  await page.getByRole('button', { name: 'Toggle fieldset' }).click();
  await expect(paused).toBeEnabled();
  await paused.focus();
  await page.keyboard.press('Space');
  await expect(paused).not.toBeChecked();
  await expect(page.getByLabel('Change requests')).toHaveText('2');
  await page.getByRole('button', { name: 'Allow reset' }).click();
  await page.getByRole('button', { name: 'Reset preferences' }).click();
  await expect(email).toBeChecked();
  await expect(paused).toBeChecked();
  await expect(sms).toBeChecked();
  await expect(page.getByLabel('Change requests')).toHaveText('2');
  expect(await values()).toEqual({ emailUpdates: 'email', smsUpdates: 'sms', pausedUpdates: 'paused' });
  expect(errors).toEqual([]);
});
