import { test, expect } from '@playwright/test';

test('mixed required inputs honor fieldset transitions and host rejection', async ({ page }) => {
  const errors: string[] = [];
  page.on('pageerror', error => errors.push(error.message));
  await page.goto('/iframe.html?id=migration-proofs-checkbox--fieldset-acceptance&viewMode=story&globals=a11y.manual:!true');
  const form = page.getByRole('form', { name: 'Checkbox fieldset form' });
  const approval = page.getByRole('checkbox', { name: 'Mixed required approval', exact: true });
  const granted = page.getByRole('checkbox', { name: 'Mixed granted approval', exact: true });
  const rejected = page.getByRole('checkbox', { name: 'Host rejected approval', exact: true });
  await expect(approval).toBeDisabled();
  await page.getByText('Mixed required approval', { exact: true }).click();
  await page.getByText('Host rejected approval', { exact: true }).click();
  await expect(page.getByLabel('Rejected requests')).toHaveText('0');
  await page.getByRole('button', { name: 'Submit approvals' }).click();
  await expect(page.getByLabel('Submitted approvals')).toHaveText('{}');
  await page.getByRole('button', { name: 'Inspect ref' }).click();
  await expect(page.getByLabel('Ref targets')).toHaveText('LABEL/INPUT');
  await page.getByRole('button', { name: 'Enable approvals' }).click();
  await expect(approval).toBeEnabled();
  await expect(approval).toBeChecked({ indeterminate: true });
  await expect(granted).toBeChecked({ indeterminate: true });
  expect(await granted.evaluate(node => (node as HTMLInputElement).validity.valueMissing)).toBe(false);
  expect(await approval.evaluate(node => (node as HTMLInputElement).validity.valueMissing)).toBe(true);
  await page.getByRole('button', { name: 'Submit approvals' }).click();
  await expect(page.getByLabel('Submitted approvals')).toHaveText('{}');
  await expect(approval).toBeFocused();
  await expect(approval).toHaveAccessibleDescription('Mixed presentation does not grant approval. Check approval to submit.');
  await page.keyboard.press('Space');
  await page.getByText('Host rejected approval', { exact: true }).click();
  await expect(page.getByLabel('Rejected requests')).toHaveText('1');
  expect(await rejected.evaluate(node => (node as HTMLInputElement).checked)).toBe(false);
  await expect(rejected).toBeChecked({ indeterminate: true });
  await page.getByRole('button', { name: 'Submit approvals' }).click();
  await expect(page.getByLabel('Submitted approvals')).toHaveText('{"approval":"yes","granted":"yes"}');
  await page.getByRole('button', { name: 'Reset approvals' }).click();
  expect(await approval.evaluate(node => (node as HTMLInputElement).checked)).toBe(false);
  await expect(approval).toBeChecked({ indeterminate: true });
  await page.getByRole('button', { name: 'Disable approvals' }).click();
  await page.getByRole('button', { name: 'Submit approvals' }).click();
  await expect(page.getByLabel('Submitted approvals')).toHaveText('{}');
  await expect(page.getByLabel('Rejected requests')).toHaveText('1');
  expect(await form.evaluate(node => (node as HTMLFormElement).checkValidity())).toBe(true);
  expect(errors).toEqual([]);
});
