import { readFile, writeFile } from 'node:fs/promises';
import { pathToFileURL } from 'node:url';

const sourcePath = new URL('../src/foundation/tokens.json', import.meta.url);
const cssPath = new URL('../src/foundation/tokens.css', import.meta.url);
const tsPath = new URL('../src/foundation/tokens.generated.ts', import.meta.url);
const name = key => `--sgui-${key.replace(/[A-Z]/g, char => `-${char.toLowerCase()}`)}`;

export function compileTokens(source) {
  const tokens = new Map();
  for (const [group, entries] of Object.entries(source)) {
    for (const [key, token] of Object.entries(entries)) {
      if (!/^[a-z][A-Za-z0-9]*$/.test(key)) throw new Error(`Invalid token name: ${key}`);
      tokens.set(`${group}.${key}`, token);
    }
  }
  function resolve(path, stack = []) {
    if (stack.includes(path)) throw new Error(`Token cycle: ${[...stack, path].join(' -> ')}`);
    const token = tokens.get(path);
    if (!token) throw new Error(`Unknown token: ${path}`);
    const alias = /^\{([^}]+)\}$/.exec(String(token.$value));
    if (alias) {
      const target = tokens.get(alias[1]);
      if (target && target.$type !== token.$type) throw new Error(`Alias type mismatch: ${path}`);
      return resolve(alias[1], [...stack, path]);
    }
    const validators = {
      color: value => /^#[\da-f]{6}([\da-f]{2})?$/i.test(value),
      dimension: value => /^(\d+(\.\d+)?)rem$/.test(value),
      duration: value => /^\d+ms$/.test(value),
      number: value => typeof value === 'number' && Number.isFinite(value),
      fontFamily: value => typeof value === 'string' && !/[;{}\n]/.test(value),
      shadow: value => typeof value === 'string' && /^\d+rem \d+(\.\d+)?rem \d+(\.\d+)?rem #[\da-f]{8}$/i.test(value),
    };
    if (!validators[token.$type]?.(token.$value)) throw new Error(`Invalid token value/type: ${path}`);
    return token.$value;
  }
  for (const path of tokens.keys()) resolve(path);
  for (const group of ['light', 'dark', 'compact', 'comfortable', 'shared']) {
    if (!source[group]) throw new Error(`Missing token group: ${group}`);
  }
  for (const [first, second] of [['light', 'dark'], ['compact', 'comfortable']]) {
    if (Object.keys(source[first]).sort().join() !== Object.keys(source[second]).sort().join()) {
      throw new Error(`Unpaired token groups: ${first}/${second}`);
    }
  }
  const declarations = group => Object.keys(source[group]).map(key => `    ${name(key)}: ${resolve(`${group}.${key}`)};`).join('\n');
  const block = (selector, group, extra = '') => `  ${selector} {\n${declarations(group)}${extra}\n  }`;
  const css = `/* Generated by scripts/tokens.mjs; edit tokens.json. */\n@layer sgui.tokens, sgui.components;\n@layer sgui.tokens {\n${block(':where([data-sgui-scope])', 'shared')}\n${block(':where([data-sgui-theme="light"], [data-sgui-theme="system"])', 'light', '\n    color-scheme: light;')}\n${block(':where([data-sgui-theme="dark"])', 'dark', '\n    color-scheme: dark;')}\n  @media (prefers-color-scheme: dark) {\n${block(':where([data-sgui-theme="system"])', 'dark', '\n    color-scheme: dark;')}\n  }\n${block(':where([data-sgui-density="compact"])', 'compact')}\n${block(':where([data-sgui-density="comfortable"])', 'comfortable')}\n}\n`;
  const keys = [...new Set(['shared', 'light', 'compact'].flatMap(group => Object.keys(source[group])))];
  const ts = `// Generated by scripts/tokens.mjs; edit tokens.json.\nexport const tokens = ${JSON.stringify(Object.fromEntries(keys.map(key => [key, `var(${name(key)})`])), null, 2)} as const;\nexport type TokenName = keyof typeof tokens;\n`;
  return { css, ts };
}

export async function generateTokens({ check = false } = {}) {
  const { css, ts } = compileTokens(JSON.parse(await readFile(sourcePath, 'utf8')));
  for (const [path, expected] of [[cssPath, css], [tsPath, ts]]) {
    if (check) {
      if (await readFile(path, 'utf8') !== expected) throw new Error(`${path.pathname} is stale; run pnpm tokens:generate`);
    } else await writeFile(path, expected);
  }
}

if (process.argv[1] && import.meta.url === pathToFileURL(process.argv[1]).href) {
  await generateTokens({ check: process.argv.includes('--check') });
}
